# Continuous Testing
#
# Run 50 times per day, split over two runs to keep individual run times
# lower so as not to hit action timeout conditions.
name: continuous
on:
  schedule:
    - cron: "0 10 * * *" # Every day at 10:00 UTC
    - cron: "30 23 * * *" # Every day at 23:30 UTC
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  preqs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3

      # Note: Using Bazel flags documented here to reduce memory footprint:
      # https://bazel.build/advanced/performance/memory
      - name: Check for flaky tests
        run: |
          bazel test \
            --test_strategy=exclusive \
            --test_output=errors \
            --runs_per_test 25 \
            --discard_analysis_cache \
            --notrack_incremental_state \
            --nokeep_state_after_build \
            --define=SANTA_BUILD_TYPE=adhoc \
            -t- \
            :unit_tests
